### ISSUE TITLE
🚂 GET - /routes endpoint - return all routes

### ISSUE THREAD

**Issue by ferminhg** [ferminhg/rock-climber-logging-app#4]
## Use case

```
When a User call endpoint `/routes`
Then returns a JSON with an array of routes
And is sorted by climbing_time desc
```

Routes model:

- `id`: UUID type
- `difficult_level`: [France level](https://es.wikipedia.org/wiki/Graduaci%C3%B3n_de_dificultad)
- `climbing_time`: timestamp
- `comments`: [LongText](https://mariadb.com/kb/en/longtext/) 

Constraints:
- `id` should be unique
- `difficult_level` and climbing_time can't be empty

## TODO

- [x] Create Domain model `Route`
- [x] Create [RouteObjectMother](https://martinfowler.com/bliki/ObjectMother.html) and test. Also, to populate the repository
- [x] Create an `InMemory` repository for models and return findAll
- [x] Inject repository on the controller using App layer
